#include "core/codecvt.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__clang__)
    #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

int main(int argc, char** argv)
{
    bool b_base64 = false;
    int arg_idx = 1;
    if (argc > 1 && strcmp(argv[1], "-base64") == 0)
    {
        b_base64 = true;
        arg_idx = 2;
    }
    if (argc != arg_idx + 2)
    {
        printf("Usage: bin2c [-base64] <outfile> <infile>\n");
        return EXIT_FAILURE;
    }
    char const* outfile_name = argv[arg_idx];
    char const* infile_name = argv[arg_idx + 1];

    // Open infile
    FILE* in = fopen(infile_name, "rb");
    if (in == NULL)
    {
        printf("Unable to open file: %s\n", infile_name);
        return EXIT_FAILURE;
    }
    fseek(in, 0L, SEEK_END);
    long const num_bytes = ftell(in);
    fseek(in, 0L, SEEK_SET);

    // Read entire file
    uint8_t* data = malloc(num_bytes > 0 ? (size_t)num_bytes : 1);
    if (data == NULL)
    {
        printf("Unable to allocate memory");
        return EXIT_FAILURE;
    }
    size_t bytes_read = fread(data, 1, num_bytes, in);
    if (bytes_read != (size_t)num_bytes)
    {
        fprintf(stderr, "Failed to read file '%s'\n", infile_name);
        return EXIT_FAILURE;
    }
    fclose(in);

    // Open outfile
    char const* p_slash = strrchr(infile_name, '/');
    if (p_slash == NULL)
    {
        p_slash = strrchr(infile_name, '\\');
    }
    char const* basename = p_slash ? p_slash + 1 : infile_name;
    size_t const n = strlen(basename);
    FILE* out = fopen(outfile_name, "wb");

    // Convert file name to variable name
    char* var_name = malloc(n + 1);
    if (var_name == NULL)
    {
        printf("Unable to allocate memory");
        return EXIT_FAILURE;
    }
    for (size_t i = 0; i < n; i++)
    {
        var_name[i] = basename[i] == '.' ? '_' : basename[i];
    }
    var_name[n] = '\0';

    // Gen
    fprintf(out, "// Generated by bin2c, don't edit!\n");
    fprintf(out, "// clang-format off\n");
    fprintf(out, "#include <stddef.h>\n");

    if (b_base64)
    {
        size_t b64_buf_len = base64_encode_size(num_bytes);
        char* b64 = malloc(b64_buf_len);
        base64_encode(b64, data, num_bytes);
        fprintf(out, "#include <stdint.h>\n\n");
        fprintf(out, "size_t bin2c_%s_size = %ld;\n", var_name, num_bytes);
        fprintf(out, "char const bin2c_%s[] =\n    \"", var_name);
        size_t b64_len = strlen(b64);
        for (size_t i = 0; i < b64_len; i++)
        {
            putc(b64[i], out);
            if ((i + 1) % 80 == 0 && i + 1 < b64_len)
                fprintf(out, "\"\n    \"");
        }
        fprintf(out, "\";\n");
        free(b64);
    }
    else
    {
        fprintf(out, "#include <stdint.h>\n\n");
        fprintf(out, "size_t bin2c_%s_size = %ld;\n\n", var_name, num_bytes);
        fprintf(out, "uint8_t bin2c_%s[] = {", var_name);
        for (uint64_t i = 0; i < (uint64_t)num_bytes; i++)
        {
            if (i % 24 == 0) fprintf(out, "\n    ");
            fprintf(out, "%d,", data[i]);
        }
        fprintf(out, "\n};\n");
    }

    free(var_name);
    free(data);
    fclose(out);
    return EXIT_SUCCESS;
}
