#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__clang__)
    #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

int main(int argc, char** argv)
{
    if (argc != 3)
    {
        printf("Usage: bin2c <outfile> <infile>\n");
        return EXIT_FAILURE;
    }
    char const* outfile_name = argv[1];
    char const* infile_name = argv[2];

    // Open infile
    FILE* in = fopen(infile_name, "rb");
    if (in == NULL)
    {
        printf("Unable to open file: %s\n", infile_name);
        return EXIT_FAILURE;
    }
    fseek(in, 0L, SEEK_END);
    const long num_bytes = ftell(in);
    fseek(in, 0L, SEEK_SET);

    // Open outfile
    char const* p_slash = strrchr(infile_name, '/');
    if (p_slash == NULL)
    {
        p_slash = strrchr(infile_name, '\\');
    }
    char const* basename = p_slash ? p_slash + 1 : infile_name;
    size_t const n = strlen(basename);
    FILE* out = fopen(outfile_name, "wb");

    // Convert file name to variable name
    char* var_name = malloc(n + 1);
    if (var_name == NULL)
    {
        printf("Unable to allocate memory");
        return EXIT_FAILURE;
    }
    for (size_t i = 0; i < n; i++)
    {
        if (basename[i] == '.')
        {
            var_name[i] = '_';
        }
        else
        {
            var_name[i] = basename[i];
        }
    }
    var_name[n] = '\0';

    // Read and gen
    fprintf(out, "// Generated by bin2c, don't edit!\n");
    fprintf(out, "// clang-format off\n");
    fprintf(out, "#include <stdint.h>\n");
    fprintf(out, "#include <stddef.h>\n\n");
    fprintf(out, "size_t bin2c_%s_size = %ld;\n\n", var_name, num_bytes);
    fprintf(out, "uint8_t bin2c_%s[] = {", var_name);
    free(var_name);
    for (uint64_t i = 0;; i++)
    {
        const size_t num_per_line = 24;
        uint8_t ch = 0;
        if ((i) % num_per_line == 0)
        {
            fprintf(out, "\n    ");
        }
        size_t num_read = fread(&ch, 1, 1, in);
        fprintf(out, "%d,", ch);
        if (num_read != 1)
        {
            break;
        }
    }
    fprintf(out, "\n};\n");
    fclose(out);
    fclose(in);
    return EXIT_SUCCESS;
}
