name: macOS Build

on:
  push:
    branches: [nightly, main]
  pull_request:
    branches: [nightly, main]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        run: ./bootstrap.sh

      - name: Build
        run: ./cup -t llvm -O3
