name: Windows Build

on:
  push:
    branches: [nightly, main]
  pull_request:
    branches: [nightly, main]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, x86]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        shell: cmd
        run: bootstrap.bat${{ matrix.arch == 'x86' && ' -arch x86' || '' }}

      - name: Build
        run: .\cup.exe -t msvc -O3
